---
version: '3.8'
services:
  myjenkins:
    image: jenkins/jenkins
    ports:
      - 5050:8080
  qaserver:
    image: tomee
    ports:
      - 6060:8080
    links:
      - myjenkins:jenkins
  prodserver:
    image: tomee
    ports:
      - 7070:8080
    links:
      - myjenkins:jenkins
...

# docker compose used to cicd jenkins and links to jekins and qa and prod
--->docker compose -f cicd.yml up -d
