---
version: '3.8'
services:
  mydb:
   image: mysql:5
   environment:
     MYSQL_ROOT_PASSWORD: ch
   volumes:
     - db: /var/lib/mysql
  myword:
    image: wordpress
    ports:
      - 6060:80
    volumes:
      - wordpress: /var/www/html
volume:
  db:
  wordpress:


...

#create volumes in path of in saves data then the paths are in docker hub
----> docker compose -f docker-compose5.yml up
