---
version: '3.8'
services:
  mydb:
   image: mysql:5
   environment:
     MYSQL_ROOT_PASSWORD: ch
  myword:
    image: wordpress
    ports:
      - 8088:80
    links:
      - mydb:mysql
...
#used to dockeer compose insatll myasql&wordpress and its both are link with links
--->docker compose -f docker-compose.yml up
---> docker compose -f docker-compose.yml dow(delete the compose file)
