---
version: '3.8'
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ch
  apache:
    image: httpd
    ports:
      - 9909:80
    links:
      - mydb:selenium
  php:
    image: php:7.2-apache
    links:
      - mydb:mysql
      - apache:httpd
...

#installation of mysql and php links its called lamp
---> docker compose -f lamp.yml up
